---
- name: "restic_exporter | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
  block:
    - name: "restic_exporter | Install the required packages for RedHat via yum"
      ansible.builtin.yum:
        name: "{{ hostvars[inventory_hostname]['restic_exporter_package'] }}"
        state: "present"
        update_cache: "yes"
      when:
        - "hostvars[inventory_hostname]['ansible_pkg_mgr'] == 'yum'"
    - name: "restic_exporter | Install the required packages for RedHat via dnf"
      ansible.builtin.dnf:
        name: "{{ hostvars[inventory_hostname]['restic_exporter_package'] }}"
        state: "present"
        update_cache: "yes"
      when:
        - "hostvars[inventory_hostname]['ansible_pkg_mgr'] == 'dnf'"
- name: "restic_exporter | Install the required packages in Debian derivatives"
  ansible.builtin.apt:
    name: "{{ hostvars[inventory_hostname]['restic_exporter_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "restic_exporter | Install the required packages in ArchLinux
    derivatives"
  community.general.pacman:
    name: "{{ hostvars[inventory_hostname]['restic_exporter_package'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
